// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: proto/remini.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Nudity represents prediction result.
type NudityReply_Nudity int32

const (
	NudityReply_UNSPECIFIED NudityReply_Nudity = 0
	NudityReply_NO_NUDITY   NudityReply_Nudity = 1
	NudityReply_NUDITY      NudityReply_Nudity = 2
)

// Enum value maps for NudityReply_Nudity.
var (
	NudityReply_Nudity_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NO_NUDITY",
		2: "NUDITY",
	}
	NudityReply_Nudity_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NO_NUDITY":   1,
		"NUDITY":      2,
	}
)

func (x NudityReply_Nudity) Enum() *NudityReply_Nudity {
	p := new(NudityReply_Nudity)
	*p = x
	return p
}

func (x NudityReply_Nudity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NudityReply_Nudity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_remini_proto_enumTypes[0].Descriptor()
}

func (NudityReply_Nudity) Type() protoreflect.EnumType {
	return &file_proto_remini_proto_enumTypes[0]
}

func (x NudityReply_Nudity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NudityReply_Nudity.Descriptor instead.
func (NudityReply_Nudity) EnumDescriptor() ([]byte, []int) {
	return file_proto_remini_proto_rawDescGZIP(), []int{2, 0}
}

// BytesRequest represents a query with only bytes on it.
type BytesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data in bytes, used to perform image verfication.
	Bytes []byte `protobuf:"bytes,1,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *BytesRequest) Reset() {
	*x = BytesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_remini_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BytesRequest) ProtoMessage() {}

func (x *BytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remini_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BytesRequest.ProtoReflect.Descriptor instead.
func (*BytesRequest) Descriptor() ([]byte, []int) {
	return file_proto_remini_proto_rawDescGZIP(), []int{0}
}

func (x *BytesRequest) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

// StringRequest represents a query with only string on it.
type StringRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Data as string, used to perform text analyzing.
	String_ string `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
}

func (x *StringRequest) Reset() {
	*x = StringRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_remini_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringRequest) ProtoMessage() {}

func (x *StringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remini_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringRequest.ProtoReflect.Descriptor instead.
func (*StringRequest) Descriptor() ([]byte, []int) {
	return file_proto_remini_proto_rawDescGZIP(), []int{1}
}

func (x *StringRequest) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

// NudityReply represents model prediction result with its confidence.
type NudityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     NudityReply_Nudity `protobuf:"varint,1,opt,name=result,proto3,enum=remini.NudityReply_Nudity" json:"result,omitempty"`
	Confidence float32            `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
}

func (x *NudityReply) Reset() {
	*x = NudityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_remini_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NudityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NudityReply) ProtoMessage() {}

func (x *NudityReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remini_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NudityReply.ProtoReflect.Descriptor instead.
func (*NudityReply) Descriptor() ([]byte, []int) {
	return file_proto_remini_proto_rawDescGZIP(), []int{2}
}

func (x *NudityReply) GetResult() NudityReply_Nudity {
	if x != nil {
		return x.Result
	}
	return NudityReply_UNSPECIFIED
}

func (x *NudityReply) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

// ToxicityReply represents model prediction about toxicity in a text.
// Multiple toxicities can be found on a single text.
type ToxicityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityHate float32 `protobuf:"fixed32,1,opt,name=identity_hate,json=identityHate,proto3" json:"identity_hate,omitempty"`
	Insult       float32 `protobuf:"fixed32,2,opt,name=insult,proto3" json:"insult,omitempty"`
	// If the prediction of neutrality is highest,
	// this means that the text does not normally contain any toxicities.
	Neutral     float32 `protobuf:"fixed32,3,opt,name=neutral,proto3" json:"neutral,omitempty"`
	Obscene     float32 `protobuf:"fixed32,4,opt,name=obscene,proto3" json:"obscene,omitempty"`
	SevereToxic float32 `protobuf:"fixed32,5,opt,name=severe_toxic,json=severeToxic,proto3" json:"severe_toxic,omitempty"`
	Threat      float32 `protobuf:"fixed32,6,opt,name=threat,proto3" json:"threat,omitempty"`
	Toxic       float32 `protobuf:"fixed32,7,opt,name=toxic,proto3" json:"toxic,omitempty"`
}

func (x *ToxicityReply) Reset() {
	*x = ToxicityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_remini_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToxicityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToxicityReply) ProtoMessage() {}

func (x *ToxicityReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_remini_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToxicityReply.ProtoReflect.Descriptor instead.
func (*ToxicityReply) Descriptor() ([]byte, []int) {
	return file_proto_remini_proto_rawDescGZIP(), []int{3}
}

func (x *ToxicityReply) GetIdentityHate() float32 {
	if x != nil {
		return x.IdentityHate
	}
	return 0
}

func (x *ToxicityReply) GetInsult() float32 {
	if x != nil {
		return x.Insult
	}
	return 0
}

func (x *ToxicityReply) GetNeutral() float32 {
	if x != nil {
		return x.Neutral
	}
	return 0
}

func (x *ToxicityReply) GetObscene() float32 {
	if x != nil {
		return x.Obscene
	}
	return 0
}

func (x *ToxicityReply) GetSevereToxic() float32 {
	if x != nil {
		return x.SevereToxic
	}
	return 0
}

func (x *ToxicityReply) GetThreat() float32 {
	if x != nil {
		return x.Threat
	}
	return 0
}

func (x *ToxicityReply) GetToxic() float32 {
	if x != nil {
		return x.Toxic
	}
	return 0
}

var File_proto_remini_proto protoreflect.FileDescriptor

var file_proto_remini_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x22, 0x24, 0x0a, 0x0c,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x97, 0x01, 0x0a, 0x0b,
	0x4e, 0x75, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x72, 0x65,
	0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x4e, 0x75, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x4e, 0x75, 0x64, 0x69, 0x74, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x22,
	0x34, 0x0a, 0x06, 0x4e, 0x75, 0x64, 0x69, 0x74, 0x79, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f,
	0x5f, 0x4e, 0x55, 0x44, 0x49, 0x54, 0x59, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x55, 0x44,
	0x49, 0x54, 0x59, 0x10, 0x02, 0x22, 0xd1, 0x01, 0x0a, 0x0d, 0x54, 0x6f, 0x78, 0x69, 0x63, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x5f, 0x68, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x48, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x69, 0x6e, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x69, 0x6e,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x6e, 0x65, 0x75, 0x74, 0x72, 0x61, 0x6c, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x62, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x07, 0x6f, 0x62, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x76, 0x65,
	0x72, 0x65, 0x5f, 0x74, 0x6f, 0x78, 0x69, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x73, 0x65, 0x76, 0x65, 0x72, 0x65, 0x54, 0x6f, 0x78, 0x69, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x68, 0x72, 0x65, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x74, 0x68, 0x72,
	0x65, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x78, 0x69, 0x63, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x74, 0x6f, 0x78, 0x69, 0x63, 0x32, 0x7b, 0x0a, 0x06, 0x52, 0x65, 0x6d,
	0x69, 0x6e, 0x69, 0x12, 0x35, 0x0a, 0x06, 0x4e, 0x75, 0x64, 0x69, 0x74, 0x79, 0x12, 0x14, 0x2e,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x4e, 0x75, 0x64,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x08, 0x54, 0x6f,
	0x78, 0x69, 0x63, 0x69, 0x74, 0x79, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x2e, 0x54, 0x6f, 0x78, 0x69, 0x63, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x3c, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x72,
	0x61, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x69, 0x61, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x2e,
	0x72, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x42, 0x0b, 0x52, 0x65, 0x6d, 0x69, 0x6e, 0x69, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_remini_proto_rawDescOnce sync.Once
	file_proto_remini_proto_rawDescData = file_proto_remini_proto_rawDesc
)

func file_proto_remini_proto_rawDescGZIP() []byte {
	file_proto_remini_proto_rawDescOnce.Do(func() {
		file_proto_remini_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_remini_proto_rawDescData)
	})
	return file_proto_remini_proto_rawDescData
}

var file_proto_remini_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_remini_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_remini_proto_goTypes = []interface{}{
	(NudityReply_Nudity)(0), // 0: remini.NudityReply.Nudity
	(*BytesRequest)(nil),    // 1: remini.BytesRequest
	(*StringRequest)(nil),   // 2: remini.StringRequest
	(*NudityReply)(nil),     // 3: remini.NudityReply
	(*ToxicityReply)(nil),   // 4: remini.ToxicityReply
}
var file_proto_remini_proto_depIdxs = []int32{
	0, // 0: remini.NudityReply.result:type_name -> remini.NudityReply.Nudity
	1, // 1: remini.Remini.Nudity:input_type -> remini.BytesRequest
	2, // 2: remini.Remini.Toxicity:input_type -> remini.StringRequest
	3, // 3: remini.Remini.Nudity:output_type -> remini.NudityReply
	4, // 4: remini.Remini.Toxicity:output_type -> remini.ToxicityReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_remini_proto_init() }
func file_proto_remini_proto_init() {
	if File_proto_remini_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_remini_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BytesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_remini_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_remini_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NudityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_remini_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToxicityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_remini_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_remini_proto_goTypes,
		DependencyIndexes: file_proto_remini_proto_depIdxs,
		EnumInfos:         file_proto_remini_proto_enumTypes,
		MessageInfos:      file_proto_remini_proto_msgTypes,
	}.Build()
	File_proto_remini_proto = out.File
	file_proto_remini_proto_rawDesc = nil
	file_proto_remini_proto_goTypes = nil
	file_proto_remini_proto_depIdxs = nil
}
